---
provider:
  name: openfaas
functions:
  spinoff:
    lang: golang-middleware
    handler: ./spinoff
    image: $DOCKER_USER/spinoff:latest
    build_args:
      GO111MODULE: true
    environment:
      read_timeout: 60s
      write_timeout: 60s
    secrets: [secret-api-key]
  spinoff-controller:
    lang: golang-middleware
    handler: ./spinoff-controller
    image: $DOCKER_USER/spinoff-controller:latest
    annotations:
      topic: cron-function
      schedule: '*/1 * * * *'
    build_args:
      GO111MODULE: true
    environment:
      read_timeout: 60s
      write_timeout: 3s
      metric_name: cpu
      metric_threshold: '50'
      last_minutes: 5
    secrets: [secret-api-key]
configuration:
  templates:
    - name: golang-middleware
