name: ci

on:
  push:
    branches: main

jobs:
  spinner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install faas-cli
        run: |
          curl -sSL https://cli.openfaas.com | sh
          sudo cp faas-cli /usr/local/bin/faas-cli
          sudo ln -sf /usr/local/bin/faas-cli /usr/local/bin/faas
      - name: Build and push spinner function
        run: |
          sed -i s/\$DOCKER_USER/${{ secrets.DOCKERHUB_USERNAME }}/g spinner.yml
          faas-cli publish -f spinner.yml

  spinner-infra-boostrap:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spinner-infra-boostrap:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
